service: cravack

frameworkVersion: "2"

provider:
  name: aws
  runtime: go1.x
  stage: ${opt:stage,'dev'}
  region: eu-central-1
  environment:
    SLACK_API_KEY: ${ssm:/cravack/${self:provider.stage}/slack-api-key}
    STRAVA_CLIENT_ID: ${ssm:/cravack/${self:provider.stage}/strava-client-id}
    STRAVA_CLIENT_SECRET: ${ssm:/cravack/${self:provider.stage}/strava-client-secret}
    STRAVA_WEBHOOK_VERIFY_TOKEN: ${ssm:/cravack/${self:provider.stage}/strava-webhook-verify-token}
    STRAVA_USER_AUTH_TABLE: "cravack-strava-authenticated-users-${self:provider.stage}"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.STRAVA_USER_AUTH_TABLE}"

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  registerStravaWebhook:
    handler: bin/registerStravaWebhook
    events:
      - httpApi:
          path: /handleStravaActivityEvent
          method: get

  handleStravaAuthenticate:
    handler: bin/handleStravaAuthenticate
    events:
      - httpApi:
          path: /handleStravaAuthenticate
          method: get

  handleStravaActivityEvent:
    handler: bin/handleStravaActivityEvent
    events:
      - httpApi:
          path: /handleStravaActivityEvent
          method: post

  handleSlackInteractionEvent:
    handler: bin/handleSlackInteractionEvent
    events:
      - httpApi:
          path: /handleSlackInteractionEvent
          method: post

  handleSlackEvent:
    handler: bin/handleSlackEvent
    events:
      - httpApi:
          path: /handleSlackEvent
          method: post

  handleSlackSlashCommand:
    handler: bin/handleSlackSlashCommand
    events:
      - httpApi:
          path: /handleSlackSlashCommand
          method: post

resources:
  Resources:
    stravaAuthenticatedUsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.STRAVA_USER_AUTH_TABLE}
        AttributeDefinitions:
          -
            AttributeName: "AthleteID"
            AttributeType: "N"
        KeySchema:
          -
            AttributeName: "AthleteID"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
